# Generated by Django 5.2.3 on 2025-12-22 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='da',
            new_name='is_deleted',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='da',
            new_name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='user',
            name='da',
        ),
    ]
