# Generated by Django 5.2.3 on 2025-12-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_rename_da_bookmark_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='sectionname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
