# Generated by Django 5.2.3 on 2025-12-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_bookmark_sectionname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='cover_image',
            new_name='article_image',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='tags',
            new_name='trailtext',
        ),
        migrations.RenameField(
            model_name='bookmark',
            old_name='url',
            new_name='weburl',
        ),
    ]
