# Generated by Django 5.2.3 on 2026-01-03 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_rename_cover_image_bookmark_article_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
